Repository raelga/extending-kubernetes, pull requests merged in 2019-09, with the labels that each got.

#5 Ansible hello-world-operator lab
  labs/ansible-operators/README.md
  labs/ansible-operators/hello-world-operator/.travis.yml
  labs/ansible-operators/hello-world-operator/Makefile
  labs/ansible-operators/hello-world-operator/README.md
  labs/ansible-operators/hello-world-operator/build/Dockerfile
  labs/ansible-operators/hello-world-operator/build/test-framework/Dockerfile
  labs/ansible-operators/hello-world-operator/build/test-framework/ansible-test.sh
  labs/ansible-operators/hello-world-operator/deploy/crds/ansiblehelloworld_v1alpha1_ansiblehelloworld_cr.yaml
  labs/ansible-operators/hello-world-operator/deploy/crds/ansiblehelloworld_v1alpha1_ansiblehelloworld_crd.yaml
  labs/ansible-operators/hello-world-operator/deploy/operator.yaml
  labs/ansible-operators/hello-world-operator/deploy/role.yaml
  labs/ansible-operators/hello-world-operator/deploy/role_binding.yaml
  labs/ansible-operators/hello-world-operator/deploy/service_account.yaml
  labs/ansible-operators/hello-world-operator/molecule/default/asserts.yml
  labs/ansible-operators/hello-world-operator/molecule/default/molecule.yml
  labs/ansible-operators/hello-world-operator/molecule/default/playbook.yml
  labs/ansible-operators/hello-world-operator/molecule/default/prepare.yml
  labs/ansible-operators/hello-world-operator/molecule/test-cluster/molecule.yml
  labs/ansible-operators/hello-world-operator/molecule/test-cluster/playbook.yml
  labs/ansible-operators/hello-world-operator/molecule/test-local/molecule.yml
  labs/ansible-operators/hello-world-operator/molecule/test-local/playbook.yml
  labs/ansible-operators/hello-world-operator/molecule/test-local/prepare.yml
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/README.md
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/defaults/main.yml
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/handlers/main.yml
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/meta/main.yml
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/tasks/main.yml
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/templates/deployment.yml.j2
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/templates/service.yml.j2
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/vars/main.yml
  labs/ansible-operators/hello-world-operator/watches.yaml
Labels: size/XL

#7 Update ansible hello-world-operator
  labs/ansible-operators/hello-world-operator/Makefile
  labs/ansible-operators/hello-world-operator/README.md
  labs/ansible-operators/hello-world-operator/deploy/crds/ansiblehelloworld_v1alpha1_ansiblehelloworld_cr.yaml
  labs/ansible-operators/hello-world-operator/deploy/operator.yaml
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/defaults/main.yml
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/templates/deployment.yml.j2
  labs/ansible-operators/hello-world-operator/roles/ansiblehelloworld/templates/service.yml.j2
  labs/ansible-operators/hello-world-operator/watches.yaml
Labels: size/L

#8 Improve/operators controllers lab
  infra/terraform/modules/gcp/dns/endpoint/main.tf
  infra/terraform/modules/gcp/dns/endpoint/variables.tf
  labs/operators-and-custom-controllers/custom-controllers/README.md
  labs/operators-and-custom-controllers/custom-controllers/kibana-certificate.yaml
  labs/operators-and-custom-controllers/custom-controllers/lab.md
  labs/operators-and-custom-controllers/custom-controllers/le-issuer.yaml
  labs/operators-and-custom-controllers/custom-controllers/le-production-issuer.yaml
  labs/operators-and-custom-controllers/custom-controllers/namespace.yaml
  labs/operators-and-custom-controllers/main.tf
  labs/operators-and-custom-controllers/operators/README.md
  labs/operators-and-custom-controllers/operators/lab.md
Labels: size/L

#9 Add demo script for ansible hello-world-operator
  labs/ansible-operators/hello-world-operator/README.md
Labels: size/M
